# Generated by Django 3.2.4 on 2023-04-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdphoto',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hdphoto',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
